[package]
name = "john-wick-bot"
version = "0.1.0"
authors = ["Waddlesworth <github@genj.io>"]
edition = "2018"

[dependencies]
"serenity" = "0.6"
"postgres" = "0.15"
"hyper" = "0.12"
"hyper-tls" = "0.3"
"mio" = "0.6"
"futures" = "0.1"
"tokio" = "0.1"
"serde_json" = "1.0"